name: flutter_login_facebook_plus
description: Login via Facebook. Easily add Facebook login feature in your application. User profile information included.
version: 2.0.2
homepage: https://github.com/arnobmonir/flutter_login_facebook_plus.git
repository: https://github.com/arnobmonir/flutter_login_facebook_plus.git
issue_tracker: https://github.com/arnobmonir/flutter_login_facebook_plus.git/issues

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  innim_lint: ^0.4.0

flutter:
  plugin:
    platforms:
      android:
        package: arnob.monir.flutter_login_facebook_plus
        pluginClass: FlutterLoginFacebookPlugin
      ios:
        pluginClass: FlutterLoginFacebookPlugin
